name: Update changelog
on:
  pull_request:
    branches: ['main']

jobs:
  check-changelog:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check if CHANGELOG.md has changed
        run: |
          FILES_CHANGED=$(git diff --name-only origin/master...HEAD | grep -E 'CHANGELOG\.md' -c)
          if [ "$FILES_CHANGED" != "2" ]; then echo "Remember to update CHANGELOG.md"; exit 1; fi;
