name: Database Migrations
on:
  push:
    branches: [main]
    paths:
      - 'src/lib/server/db/**'

jobs:
  migrate:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Run migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
          AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
          OAUTH_DISCORD_CLIENT_ID: ${{ secrets.OAUTH_DISCORD_CLIENT_ID }}
          OAUTH_DISCORD_CLIENT_SECRET: ${{ secrets.OAUTH_DISCORD_CLIENT_SECRET }}
          OAUTH_DISCORD_REDIRECT_URI: ${{ secrets.OAUTH_DISCORD_REDIRECT_URI }}
          OAUTH_GITHUB_CLIENT_ID: ${{ secrets.OAUTH_GITHUB_CLIENT_ID }}
          OAUTH_GITHUB_CLIENT_SECRET: ${{ secrets.OAUTH_GITHUB_CLIENT_SECRET }}
          OAUTH_GITHUB_REDIRECT_URI: ${{ secrets.OAUTH_GITHUB_REDIRECT_URI }}
          TICKET_API_URL: ${{ secrets.TICKET_API_URL }}
          PUBLIC_BASE_URL: ${{ vars.PUBLIC_BASE_URL }}
          DB_MIGRATING: true
        run: npm run db:migrate
